name: "Cargo"
description: "Runs the given `cargo` command with support for GitHub Annotations."
inputs:
  cargo-command:
    description: "Cargo command"
    required: true
  with-annotation:
    description: "Enable Github Annotations"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: cargo
      run: |
        CMD="cargo"

        if [[ "${{ inputs.cargo-command }}" != "" ]]; then
          CMD="$CMD ${{ inputs.cargo-command }}"
        fi

        if [[ "${{ inputs.with-annotation }}" == "true" ]]; then
          if [[ "$CMD" == *"-- -D warnings"* ]]; then
            CMD="${CMD/-- -D warnings/} --message-format=json -- -D warnings"
          else
            CMD="$CMD --message-format=json"
          fi
          CMD="$CMD | ${{ github.action_path }}/annotation.sh"
        fi

        eval "$CMD"
      shell: bash
