name: "Cargo"
description: "Runs the given `cargo` command with support for GitHub Annotations."
inputs:
  cargo-command:
    description: "Cargo command"
    required: true
  with-annotation:
    description: "Enable Github Annotations"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: cargo
      run: python $GITHUB_ACTION_PATH/annotation.py
      shell: bash
      env:
        INPUT_CARGO_COMMAND: ${{ inputs.cargo-command }}
        WITH_ANNOTATION: ${{ inputs.with-annotation }}
