name: "Cargo Clippy"
description: "Runs `cargo clippy` with optional extra commands and GitHub annotation support for inline diagnostics."
inputs:
  cargo-command:
    description: "Clippy extra arguments"
    default: ""
  with-annotation:
    description: "Enable Clippy annotation"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: cargo clippy
      run: |
        CMD="cargo clippy"

        if [[ "${{ inputs.cargo-command }}" != "" ]]; then
          CMD="$CMD ${{ inputs.cargo-command }}"
        fi

        if [[ "${{ inputs.with-annotation }}" == "true" ]]; then
          CMD="$CMD --message-format=json | ${{ github.action_path }}/clippy-annotation.sh"
        fi

        eval "$CMD"
      shell: bash
