name: "Clippy Annotation"
description: "Github inline annotation for clippy"
inputs:
  features:
    description: "Clippy feature to use"
    required: false
    default: ""
  platform-target:
    description: "Clippy platform target"
    required: false
    default: "x86_64-unknown-linux-gnu"
  with-annotation:
    description: "Enable Clippy annotation"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: clippy (with annotations)
      if: inputs.with-annotation == 'true'
      run: |
        cargo clippy --features "$FEATURES" --target "$PLATFORM" --message-format=json \
        | ${{ github.action_path }}/clippy-annotation.sh
      shell: bash
      env:
        FEATURES: ${{ inputs.features }}
        PLATFORM: ${{ inputs.platform-target }}

    - name: clippy (without annotation)
      if: inputs.with-annotation != 'true'
      run: cargo clippy --features "$FEATURES" --target "$PLATFORM"
      shell: bash
      env:
        FEATURES: ${{ inputs.features }}
        PLATFORM: ${{ inputs.platform-target }}
