name: "Clippy Annotation"
description: "Github inline annotation for clippy"
inputs:
  commands:
    description: "Clippy extra arguments"
    default: ""
  with-annotation:
    description: "Enable Clippy annotation"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: clippy
      run: |
        CMD="cargo clippy"

        if [[ "${{ inputs.commands }}" != "" ]]; then
          CMD="$CMD ${{ inputs.commands }}"
        fi

        if [[ "${{ inputs.with-annotation }}" == "true" ]]; then
          CMD="$CMD --message-format=json | ${{ github.action_path }}/clippy-annotation.sh"
        fi

        eval "$CMD"
      shell: bash
